First commit
tivi2105/MRDB_Project pull request #1
Opened 2022-02-22 04:29 UTC by tivi2105

Hi Guru,
Basic setup for our project is done, please review and let me know if any changes are required.
Thanks

2022-02-23 13:52 UTC, gurusrikar requested changes
Mostly looks good. Suggested a few changes.

2022-02-23 13:52 UTC, gurusrikar commented on src/main/java/com/mrdb/MrdbVersion1Application.java
> +public class MrdbVersion1Application {
Including version numbers in this main application class is a bad idea. When a new version of the app is published, the class name needs to be updated to Version2. So, we should rename this to be more generic
Just - `MrdbApplication`

2022-02-23 13:52 UTC, gurusrikar commented on src/mrdb_frontend/jsconfig.json
> +}
`src/mrdb_frontend/node/node.exe`
This file below should not be committed to git repository. It should only exist in local (add it to gitignore file)

2022-02-23 13:52 UTC, gurusrikar commented on src/mrdb_frontend/src/components/HelloWorld.vue
> +</style>
missing a new empty line here

2022-02-23 13:52 UTC, gurusrikar commented on src/mrdb_frontend/vue.config.js
> +}
same as above;
missing a new empty line here

2022-02-23 13:52 UTC, gurusrikar commented on src/test/java/com/mrdb/MrdbVersion1ApplicationTests.java
> +class MrdbVersion1ApplicationTests {
same comment about including version number in class names

2022-02-24 23:45 UTC, tivi2105 commented
@gurusrikar suggested changes were made, please take a look and review.

2022-02-25 01:28 UTC, gurusrikar approved these changes

2022-02-25 01:28 UTC, merged